// Character content preserved from Drakvalvet v021.
export const raceData = {
  human: {
    label: 'Människa',
    desc: 'Anpassningsbar och envis. Jämn styrka i allt.',
    bonus: 'STY +1, SMI +1, KON +1, INT +1, VIS +1, KAR +1',
    mods: { str: 1, dex: 1, con: 1, int: 1, wis: 1, cha: 1 },
    hpBonus: 0,
    acBonus: 0,
  },
  elf: {
    label: 'Alv',
    desc: 'Kvicktänkt och lättfotad, med skarpa sinnen.',
    bonus: 'SMI +2, INT +1',
    mods: { str: 0, dex: 2, con: 0, int: 1, wis: 0, cha: 0 },
    hpBonus: 0,
    acBonus: 1,
  },
  dwarf: {
    label: 'Dvärg',
    desc: 'Härdad och stryktålig, van vid mörker och sten.',
    bonus: 'KON +2, STY +1',
    mods: { str: 1, dex: 0, con: 2, int: 0, wis: 0, cha: 0 },
    hpBonus: 2,
    acBonus: 0,
  },
  halfling: {
    label: 'Halvling',
    desc: 'Liten, snabb och förvånansvärt övertalande.',
    bonus: 'SMI +2, KAR +1',
    mods: { str: 0, dex: 2, con: 0, int: 0, wis: 0, cha: 1 },
    hpBonus: 0,
    acBonus: 1,
  },
} as const;

export const classData = {
  warrior: {
    label: 'Krigare',
    desc: 'Lever på stål och envishet.',
    bonus: 'Vapen: Svärd (d8) · Livstärning d10 · Klassförmåga: Skydda',
    base: { str: 15, dex: 11, con: 14, int: 9, wis: 10, cha: 10 },
    maxHp: 16,
    ac: 14,
    attack: 5,
    damage: [1, 8, 2],
    damageType: 'Hugg',
    weapon: 'Svärd (d8)',
    armor: 'Läderbrynja',
    shield: false,
    potions: 2,
    herbs: 0,
  },
  mage: {
    label: 'Magiker',
    desc: 'Formar lågan med tanken.',
    bonus: 'Vapen: Eldpil (d8) · Livstärning d6 · Klassförmåga: Brinnande händer',
    base: { str: 9, dex: 12, con: 11, int: 16, wis: 13, cha: 10 },
    maxHp: 11,
    ac: 12,
    attack: 5,
    damage: [1, 8, 1],
    damageType: 'Eld',
    weapon: 'Eldpil (d8)',
    armor: 'Resekappa',
    shield: false,
    potions: 2,
    herbs: 1,
  },
  thief: {
    label: 'Tjuv',
    desc: 'Slår till där ingen ser.',
    bonus: 'Vapen: Dolk (d6) · Livstärning d8 · Klassförmåga: Smygattack',
    base: { str: 11, dex: 15, con: 12, int: 12, wis: 11, cha: 12 },
    maxHp: 13,
    ac: 15,
    attack: 5,
    damage: [1, 6, 2],
    damageType: 'Stick',
    weapon: 'Dolk (d6)',
    armor: 'Mjuk läderrustning',
    shield: false,
    potions: 2,
    herbs: 0,
  },
  cleric: {
    label: 'Kleriker',
    desc: 'Bär ett ljus som inte slocknar.',
    bonus: 'Vapen: Stridsklubba (d6) · Livstärning d8 · Klassförmåga: Helande ord',
    base: { str: 13, dex: 10, con: 13, int: 11, wis: 15, cha: 12 },
    maxHp: 14,
    ac: 14,
    attack: 4,
    damage: [1, 6, 2],
    damageType: 'Kross',
    weapon: 'Stridsklubba (d6)',
    armor: 'Brynja av ringläder',
    shield: true,
    potions: 2,
    herbs: 1,
  },
  ranger: {
    label: 'Ranger',
    desc: 'Spårar bytet genom Gråskogen och fäller det på avstånd.',
    bonus:
      "Vapen: Longbow (d8, 150/600 ft) och Shortsword (d6) · Livstärning d10 · Klassförmåga: Hunter's Mark",
    base: { str: 12, dex: 15, con: 13, int: 8, wis: 14, cha: 10 },
    // D&D 2024 rules scale: HP, AC, attack and damage are derived from the ability scores.
    rules: { hitDie: 10, armorBase: 12, proficiency: 2, attackAbility: 'dex' },
    maxHp: 10,
    ac: 12,
    attack: 2,
    damage: [1, 8, 0],
    damageType: 'Stick',
    weapon: 'Longbow (d8)',
    armor: 'Studded Leather',
    shield: false,
    potions: 2,
    herbs: 1,
  },
} as const;

export const talentData = {
  iron: {
    label: 'Stålsinne',
    desc: 'Du är svår att fälla och får mer uthållighet.',
    bonus: '+4 max HP',
    hpBonus: 4,
    attackBonus: 0,
    acBonus: 0,
    potions: 0,
    herbs: 0,
  },
  keen: {
    label: 'Skarp blick',
    desc: 'Du läser striden bättre än de flesta.',
    bonus: '+1 på attacker',
    hpBonus: 0,
    attackBonus: 1,
    acBonus: 0,
    potions: 0,
    herbs: 0,
  },
  supply: {
    label: 'Packråtta',
    desc: 'Du reser alltid bättre förberedd än andra.',
    bonus: '+1 hälsodryck, +1 ört',
    hpBonus: 0,
    attackBonus: 0,
    acBonus: 0,
    potions: 1,
    herbs: 1,
  },
} as const;
